manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: infused-kim
      url-base: https://github.com/infused-kim
    - name: badjeff
      url-base: https://github.com/badjeff
    - name: dhruvinsh
      url-base: https://github.com/dhruvinsh
  projects:
    - name: zmk
    # Uncomment to use PS/2 mouse listener module from infused-kim instead of zmkfirmware
      remote: infused-kim
      revision: pr-testing/mouse_ps2_module_base
      # remote: zmkfirmware
      # revision: v0.3
      import: app/west.yml
    # Module for PS/2 mouse & TP driver
    # - name: kb_zmk_ps2_mouse_trackpoint_driver
    #   remote: infused-kim
    #   revision: main
    - name: kb_zmk_ps2_mouse_trackpoint_driver
      remote: badjeff
      revision: main
    # - name: zmk-tri-state
    #   remote: dhruvinsh
    #   revision: main
  self:
    path: config